# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
url: "http://justme0.com/"
#baseurl: "/contrast" # comment out if in root directory
title: "Justme0 的博客"
author: "Justme0"
#email: "kenmux@gmail.com"
description: "撷英采华，以备不需"
#subheading: "Really cool blog about ... something"

# This is the default format:
# permalink: /:categories/:year/:month/:day/:title.html
#
# For more see: http://jekyllrb.com/docs/permalinks/
#
permalink: /archive/:title.html

# Don't include protocol, just the domain
#enforce_ssl: justme0.com

# Jekyll build & syntax highlighting settings
#
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
highlighter: rouge

markdown: kramdown # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

#markdown: redcarpet
#redcarpet:
#    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]

# Settings for <!-- more --> tag
#
excerpt_separator: "<!-- more -->"
more: More

# Settings for comments helper
#
comments:
    disqus: "xiwan"
    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#eeeeee"
        even: "#222222"

links:
    - github: "https://github.com/justme0"
    - csdn: "http://blog.csdn.net/justme0"
#    - twitter: "https://twitter.com/kenmuxlee/"
#    - google-plus: "https://plus.google.com/+KenmuxDe"
#    - reddit: "https://www.reddit.com/user/kenmux/"
#    - youtube: "https://www.youtube.com/user/kenmux"
#    - steam: "http://steamcommunity.com/id/kenmux/"
#    - facebook: "https://facebook.com/kenmux/"
#    - rss: "https://xiwan.info/feed.xml"

# Settings for pagination
#
#paginate: 10
#paginate_path: "/archives/page/:num"

# Some other limits
post_limit: 10
rss_limit: 5

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
#
date_format: "ordinal"

# Define the order of pages in the navigation bar
#
nav_pages: ["Home", "Archive", "About"]
